bbs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=254)
    category = models.ForeignKey('Category')
    content = models.TextField(max_length=10240)
    author = models.ForeignKey('UserProfile')
    publish_date = models.DateTimeField(auto_now_add=True)
    brief = models.TextField(max_length=256)
    #thumb_up = models.ForeignKey('Thumb_up',blank=True)
    #comments = models.ManyToManyField('Comment',blank=True,related_name='article_to_comment')
    head_img = models.ImageField(upload_to='statics/imgs/upload')

    def __unicode__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(unique=True,max_length=64)
    admins = models.ManyToManyField('UserProfile')

    def __unicode__(self):
        return self.name

class ThumbUp(models.Model):
    article = models.ForeignKey('Article')
    user = models.ForeignKey('UserProfile')
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.article

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=32)
    user_groups = models.ManyToManyField('UserGroup')
    friends = models.ManyToManyField('self',related_name='my_friends')

    def __unicode__(self):
        return '%s' %(self.user)

class UserGroup(models.Model):
    name = models.CharField(max_length=32,unique=True)

    def __unicode__(self):
        return self.name

class Comment(models.Model):
    article = models.ForeignKey('Article')
    user = models.ForeignKey('UserProfile')
    date = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(max_length=1024)
    parent_comment = models.ForeignKey('self',blank=True,null=True,related_name='pid')

    def __unicode__(self):
        return self.comment

bbs/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
import models
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist
import  utility
import json
from django.contrib.auth import authenticate,login,logout
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



# Create your views here.



def account_login(request):

    if request.method == 'GET':
        return  render(request,'login.html')

    else:
        print request.POST
        username = request.POST.get('username')
        passwd = request.POST.get('password')
        user = authenticate(username=username,password=passwd)
        if user is not None:
            login(request,user)
            user.userprofile.online = True
            user.userprofile.save()
            return  HttpResponseRedirect("/")
        else:
            return  render(request,'login.html',{
                'login_err': "Wrong username or password!"
            })

def account_logout(request):
    logout(request)
    return render(request,'login.html')

def index(request):
    article_list = models.Article.objects.all().order_by("-id")
    paginator = Paginator(article_list, 2)  # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles = paginator.page(paginator.num_pages)

    return render(request,'index.html',{
        'articles': articles
    })


def create_article(request):
    if request.method == 'POST':
        # print request.POST
        article = utility.Bbs_generater(request)
        bbs = article.create()
        html_res = '''Article <a href="/detail/%s/">%s</a> is created successful! ''' % (bbs.id,bbs.title)
        return HttpResponse(html_res)
    elif request.method == 'GET':
        category = models.Category.objects.all()
        return render(request,'create_article.html',{'category':category})

def life(request):

    return  render(request,'life.html')

def tech(request):

    return  render(request,'tech.html')
def category1024(request):
    aaa = 'aaa'
    return  render(request,'1024.html',{'aaa':aaa})

def detail(request,article_id):
    try:
        article = models.Article.objects.get(id=article_id)
        comment = utility.create_comment_tree(request,article_id)
    except ObjectDoesNotExist,e:
        err_msg = str(e)

    return render(request,'article.html',{'article':article,'comment':comment})

def thumb_up(request,article_id):
    try:
        article = models.Article.objects.get(id=article_id)
    except ObjectDoesNotExist,e:
        err_msg = str(e)

    user = request.user.userprofile
    data_list = {
    'user' : user,
    'article' : article,
    }
    thumb = models.ThumbUp(**data_list)
    thumb.save()
    return HttpResponseRedirect('/')

templates/1024.html
{% extends 'index.html' %}


{% block content-left %}

    1024

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

templates/article.html
{% extends 'index.html' %}
    <!-- Page Content -->
    {% block page-container %}
    <div class="container">
        {% block container %}
        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-md-8">
                {% block content-left %}
                    <div class="row">
                        <h1>{{ article.title }}</h1>
                    </div>
                    <div class="author">
                         <span>{{ article.author }}</span>
                         <span>{{ article.publish_date }}</span>
                         <span><i class="fa fa-commenting-o" aria-hidden="true">{{ article.comment_set.select_related.count }}</i></span>
                         <span><i class="fa fa-thumbs-up" aria-hidden="true"></i>{{ article.thumbup_set.select_related.count }}</span>
                         <span><i class="fa fa-weixin" aria-hidden="true"></i></span>
                    </div>
                    <div class="blog-content">
                        {% autoescape off %}
                        {{ article.content }}
                        {% endautoescape %}
                    </div>
                    <div>
                        {% load custom %}
                        {% autoescape off %}
                        {% create_tree comment 10 %}
                        {% endautoescape %}
                    </div>
                {% endblock %}
            </div>


                {% block content-right %}



                {% endblock %}


        <!-- /.row -->

        <hr>
        {% endblock %}
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    {% endblock %}

    {% block bottom-js %}

    {% endblock %}

templates/create_article.html
{% extends 'index.html' %}


{% block content-left %}

<form method="post" action="{% url 'create_article' %}" enctype="multipart/form-data">{% csrf_token %}
  <div class="form-group">
    <label for="title">文章标题</label>
    <input type="title" class="form-control" id="title" placeholder="title" name="title">
  </div>
    <div class="form-group">
      <label for="name">文章分类</label>
      <select class="form-control" name="cate_id">
          {% for cate in category %}
         <option value="{{ cate.id }}">{{ cate.name }}</option>
          {% endfor %}
      </select>
    </div>
  <div class="form-group">
    <label for="brief">摘要</label>
    <input type="brief" class="form-control" id="brief" placeholder="brief" name="brief">
  </div>
  <div class="form-group">
    <label for="content">文章内容</label>
    <textarea name="content" id="content" placeholder="content"></textarea>
  </div>
  <div class="form-group">
    <label for="title_img">File input</label>
    <input type="file" id="title_img" name="title_img">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

    {% block bottom-js %}
        <script type="text/javascript" src="/static/plugins/tinymce/js/tinymce/tinymce.min.js"></script>
        <script>tinymce.init({ selector:'textarea' });</script>
    {% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Post - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
    <!-- Custom CSS -->
    <link href="/static/css/blog-post.css" rel="stylesheet">
    <link href="/static/css/custom.css" rel="stylesheet">
    <link href="/static/css/bootstrap.vertical-tabs.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block head-css %}
    {% endblock %}

</head>

<body>


    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">TOP</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul id="top_menu" class="nav navbar-nav">
                    <li>
                        <a href="/">全部</a>
                    </li>
                    <li>
                        <a href="{% url 'life' %}">生活</a>
                    </li>
                    <li>
                        <a href="{% url 'tech' %}">技术</a>
                    </li>
                    <li>
                        <a href="{% url 'category1024' %}">1024</a>
                    </li>
                    <li>
                        <a href="{% url 'chat_index' %}">聊天室</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'create_article' %}">发帖</a>
                    </li>
                    <li>
                        <a href="#">{{ request.user.userprofile.name }}</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">登出</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">登录/注册</a>
                    </li>
                    {% endif %}

                </ul>

            </div>
            <!-- /.navbar-collapse -->

        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    {% block page-container %}
    <div class="container">
        {% block container %}
        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-md-8">
                {% block content-left %}
                    <div class="row">
                        {% for article in articles %}
                        <div style="border-bottom: 1px goldenrod dotted;padding-top: 20px" class="row">
                            <div class="head-img col-md-4 row" style="padding-bottom: 2px">
                                <img src="{{ article.head_img }}"/>
                            </div>
                            <div class="col-md-8 row">
                                <div>
                                    <a href="{% url 'detail' article.id %}"><h3>{{ article.title }}</h3></a>
                                </div>
                                 <div class="author">
                                     <span>{{ article.author.name }}</span>
                                     <span>{{ article.publish_date }}</span>
                                     <span><a href="#"><i class="fa fa-commenting-o" aria-hidden="true"></i></a>{{ article.comment_set.select_related.count }}</span>
                                     <span><a href="thumb_up/{{ article.id }}/"><i class="fa fa-thumbs-up" aria-hidden="true"></i></a>{{ article.thumbup_set.select_related.count }}</span>
                                     <span><i class="fa fa-weixin" aria-hidden="true"></i></span>
                                </div>
                                <div class="breif">
                                    {{ article.brief }}
                                </div>
                            </div>


                        </div>
                        {% endfor %}
                    </div>

                    <div>
                        <div style="text-align: center">
                            <nav>
                                <ul class="pagination">
                                    <li>
                                        {% if articles.has_previous %}
                                        <a href="?page={{ articles.previous_page_number }}" aria-label="Previous">
                                            <span aria-hidden="true">上一页</span>
                                        </a>
                                        {% endif %}
                                    </li>
                                        {% if articles.number > 10 %}
                                            {% for page_num in articles.paginator.page_range %}
                                                {% if page_num == 2 %}
                                                    <li><a href="">…</a></li>
                                                {% elif page_num > 2 and page_num|add:'5' < articles.number %}
                                                    {{ pass }}
                                                {% elif page_num == articles.count|add:'-1' %}
                                                    <li><a href="">…</a></li>
                                                {% elif page_num < articles.count|add:'-1' and page_num|add:'-5' > articles.number %}
                                                    {{ pass }}
                                                {% else %}
                                                    <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                        {% else %}
                                            {% for page_num in articles.paginator.page_range %}
                                                {% if page_num == articles.number %}
                                                    <li class="active"><a href="#">{{ page_num }}</a></li>
                                                {% else %}
                                                    <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    {% if articles.has_next %}
                                     <li>
                                        <a href="?page={{ articles.next_page_number }}" aria-label="Next">
                                            <span aria-hidden="true">下一页</span>
                                        </a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                {% endblock %}
            </div>


            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">
                {% block content-right %}
                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>
                {% endblock %}
            </div>

        </div>
        <!-- /.row -->

        <hr>
        {% endblock %}
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    {% endblock %}
    <!-- /.container -->

    <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>
    {% block bottom-js %}
    <script type="text/javascript">


    </script>

    {% endblock %}
<script type="text/javascript">

    $(document).ready(function(){

        $("#top_menu a").each(function(){

            if ($(this).attr("href") == "{{ request.path }}"){
                $(this).parent().addClass("active");
            };
        });//end each

        /*

        */






    });// end doc ready

</script>

</body>

</html>

templates/life.html
{% extends 'index.html' %}


{% block content-left %}

    生活页

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

templates/login.html
{% extends 'index.html' %}

{% block container %}
<div>
    <form method="post" action="{% url 'login' %}">{% csrf_token %}

        <input type="text" name="username" placeholder="username" />
        <input type="password" name="password" placeholder="password" />
        <input type="submit" value="Login" class="btn btn-success" />

    </form>

    <p style="color: red">{{ login_err }}</p>
</div>

{% endblock %}

templates/tech.html
{% extends 'index.html' %}


{% block content-left %}

    technique

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

templates/webqq/chat_index.html
{% extends 'index.html' %}


{% block content-left %}

    webqq

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}